/**
 * Terms of Service Page
 *
 * Legal terms and conditions for using the Mengo platform.
 */

'use client';

import React from 'react';
import Link from 'next/link';
import { Logo } from '@/components/ui/Logo';

export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-[#0d1117] py-12 px-4">
      <div className="max-w-3xl mx-auto">
        {/* Logo */}
        <div className="flex justify-center mb-10">
          <Logo size="lg" />
        </div>

        <h1 className="text-3xl font-bold text-white mb-2">Terms of Service</h1>
        <p className="text-sm text-[#686f7e] mb-10">Last updated: May 2026</p>

        <div className="space-y-8 text-[#afb6c4] text-sm leading-relaxed">
          <section>
            <h2 className="text-lg font-semibold text-white mb-3">1. Acceptance of Terms</h2>
            <p>
              By accessing or using the Mengo platform (&quot;Service&quot;), you agree to be bound by these Terms of Service (&quot;Terms&quot;). If you do not agree to these Terms, you may not access or use the Service. These Terms apply to all visitors, users, and others who access or use the Service.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">2. Description of Service</h2>
            <p>
              Mengo is an AI-powered Chief Marketing Officer platform that provides marketing strategy, content generation, brand management, and related tools. The Service includes, but is not limited to, AI-generated marketing content, campaign planning, social media management, brand asset creation, and analytics.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">3. User Accounts</h2>
            <p>
              To use certain features of the Service, you must create an account. You are responsible for safeguarding your account password and for all activities that occur under your account. You agree to notify Mengo immediately of any unauthorized use of your account. You must provide accurate, current, and complete information during registration and keep your account information updated.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">4. Acceptable Use</h2>
            <p>You agree not to use the Service to:</p>
            <ul className="list-disc list-inside mt-2 space-y-1">
              <li>Violate any applicable laws or regulations</li>
              <li>Infringe upon the intellectual property rights of others</li>
              <li>Generate misleading, harmful, or fraudulent content</li>
              <li>Distribute spam, malware, or other harmful materials</li>
              <li>Attempt to gain unauthorized access to any part of the Service</li>
              <li>Use the Service in any way that could damage, disable, or impair its operation</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">5. AI-Generated Content</h2>
            <p>
              The Service uses artificial intelligence to generate marketing content, strategies, and recommendations. You acknowledge that AI-generated content may not always be accurate, complete, or suitable for your specific needs. You are solely responsible for reviewing, editing, and approving any AI-generated content before publishing or distributing it. Mengo does not guarantee the accuracy, quality, or fitness for purpose of AI-generated outputs.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">6. Intellectual Property</h2>
            <p>
              You retain ownership of all content you input into the Service. Content generated by the Service using your input is owned by you, subject to the rights granted in these Terms. You grant Mengo a limited, non-exclusive license to process your input solely for the purpose of providing the Service. Mengo reserves all rights in the Service itself, including its design, branding, and underlying technology.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">7. Data and Privacy</h2>
            <p>
              Your use of the Service is also governed by our{' '}
              <Link href="/privacy-policy" className="text-[#C8FF2E] hover:text-[#d4ff5c]">
                Privacy Policy
              </Link>
              , which describes how we collect, use, and protect your personal information. By using the Service, you consent to the collection and use of your data as described in our Privacy Policy.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">8. Limitation of Liability</h2>
            <p>
              To the maximum extent permitted by law, Mengo shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising out of or relating to your use of the Service. This includes, but is not limited to, damages for loss of profits, data, or other intangible losses. Our total liability shall not exceed the amount you paid for the Service in the twelve months preceding the claim.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">9. Termination</h2>
            <p>
              We may terminate or suspend your account and access to the Service at our sole discretion, without prior notice, for conduct that we believe violates these Terms or is harmful to other users, us, or third parties. Upon termination, your right to use the Service will immediately cease. Provisions that by their nature should survive termination shall remain in effect.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">10. Changes to Terms</h2>
            <p>
              We reserve the right to modify or replace these Terms at any time. If a revision is material, we will provide at least 30 days&apos; notice before the new Terms take effect. What constitutes a material change will be determined at our sole discretion. Your continued use of the Service after any changes constitutes acceptance of the new Terms.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">11. Contact</h2>
            <p>
              If you have any questions about these Terms, please contact us at{' '}
              <a href="mailto:support@mengo.ai" className="text-[#C8FF2E] hover:text-[#d4ff5c]">
                support@mengo.ai
              </a>
              .
            </p>
          </section>
        </div>

        <div className="mt-12 pt-8 border-t border-white/10 text-center">
          <p className="text-sm text-[#686f7e]">
            &copy; {new Date().getFullYear()} Mengo. All rights reserved.{' '}
            <Link href="/privacy-policy" className="text-[#C8FF2E] hover:text-[#d4ff5c]">
              Privacy Policy
            </Link>
          </p>
        </div>
      </div>
    </div>
  );
}